name: Deploy Backend to EC2

on:
  push:
    branches:
      - '**'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # - name: Change to backend directory
      #   run: cd backend

      - name: Install dependencies
        working-directory: backend
        run: npm install

      - name: Build backend
        working-directory: backend
        run: npm run build
      
      - name: Save build as artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-build
          path: backend/dist

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      # - name: Change to backend directory
      #   run: cd backend

      - name: Install dependencies
        working-directory: backend
        run: npm install

      - name: Verify Jest installation
        working-directory: backend
        run: npx jest --version

      - name: Run tests
        working-directory: backend
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Change to backend directory
        run: cd backend

      - name: Install dependencies
        run: npm install

      - name: Restore build from artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-build
          path: backend/dist

      - name: Deploy to EC2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          EC2_INSTANCE_IP: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
            # Instalar Node.js y PM2 si no están instalados
            sudo apt update
            sudo apt install -y nodejs npm
            sudo npm install -g pm2

            # Crear carpeta de la aplicación y copiar archivos
            mkdir -p ~/backend
          '
          scp -o StrictHostKeyChecking=no -i private_key.pem -r backend/* ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/backend/
          
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
            cd ~/backend
            npm ci --production
            npx prisma generate
            pm2 delete backend || true
            pm2 start dist/index.js --name backend
          '
          rm private_key.pem